---
title: "Dengue Risk Maps of México"
output: 
  flexdashboard::flex_dashboard:
      theme: flatly
output_dir: docs
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

options(shiny.maxRequestSize=30*1024^2)
# Packages
library(formattable)
library(tmap)
library(rmarkdown)
library(knitr)
library(shiny)
library(flexdashboard)
library(plotly)
library(boldenr)
library(stringr)
library(magrittr)
library(leaflet)
library(dash)
library(ECharts2Shiny)

```


```{r, data, include=FALSE}

# Step 1. load the hotspots dengue cases ####
load("C:/Users/felip/OneDrive/proyects/hotspots/8.RData/cases_hotspots_agebs19.RData")

cases_hotspots_agebs19 <- cases_hotspots_agebs19 |> sf::st_make_valid()

# Step 2 load the eggs hotspots #### 
load("C:/Users/felip/OneDrive/proyects/hotspots/8.RData/eggs_hotspots_historic/30_veracruz/result_veracruz_zinb1.RData")

# Step  load the block dataset ###
#blocks <- rgeomex::blocks_ine20_mx_centroid |>sf::st_as_sf(coords = c("x", "y"), crs = 4326)

# Step 3. load the risk_ageb function ####
source('C:/Users/felip/Dropbox/r_developments/r_dashboards/github_pages/test_dashboard/3.Functions/risk_agebs.R')

# Step 4. load the risk_map function ####
source("C:/Users/felip/OneDrive/proyects/hotspots/3.Functions/risk_map.R")

# Step 5. load the hotspots map ####
source("C:/Users/felip/Dropbox/r_developments/r_dashboards/github_pages/test_dashboard/3.Functions/hotspots_map.R")

# Step 6. create the function for extract the locality ####
extract_locality <- function(cve_edo, locality){
    rgeomex::loc_inegi19_mx%>%
        dplyr::filter(CVE_ENT %in% c(cve_edo)) %>%
        dplyr::filter(NOMGEO %in% c(rgeomex::find_most_similar_string(locality, unique(NOMGEO)))) %>%
        sf::st_make_valid()
}


```

**Dengue Transmission Hotspots**
=====================================  

Column {.tabset}
-------------------------------------

### **<span style="color:#990000">Panuco</span>**

```{r, hotspots_dengue_panuco, echo=FALSE}
hotspots_map(cve_ent = "30",
             locality = "Pánuco",
             hotspots = cases_hotspots_agebs19,
             static_map = FALSE)


```


### **<span style="color:#990000">Tuxpan</span>**
<html>
<head>
<style>
body {
  margin: 0px;
}

.wrapper {
    display: grid;
    grid-gap: 2px;
    grid-template-columns: 280px 280px 280px 550px;
    grid-template-rows: 165px 165px 165px 165px;
    background-color: #fff;
    color: "green";
  }

  .box {
    background-color: #cfcfc4;
    color: "green";
    border-radius: 2px;
    padding: 5px;
    font-size: 100%;

  }

  .a {
    grid-column: 1 / 4;
    grid-row: 1 / 4;
  }
  .b {
    grid-column: 4 ;
    grid-row: 1 / 3;
  }
  .c {
    grid-column: 4 ;
    grid-row: 3 / 5 ;
  }
  .d {
    grid-column: 3;
    grid-row: 4;
  }
  .e {
    grid-column: 2;
    grid-row: 4;
  }
  .f {
    grid-column: 1;
    grid-row: 4;
  }
</style>
</head>
<body>
<div class="wrapper">
  <div class="box a">
```{r hotspots_dengue_tuxpan}
hotspots_map(cve_ent = "30",
             locality = "Tuxpan de Rodriguez Cano",
             hotspots = cases_hotspots_agebs19,
             static_map = FALSE)

```
  </div>
  <div class="box b">
```{r forest_plot_tuxpan, dpi = 300, fig.height= 5,fig.width = 7,fig.align = "center", out.height='100%', out.width = '100%',fig.show = "hold"}
 
# extract the locality
loc <- extract_locality(cve_edo = "30",
                        locality = "Tuxpan de Rodríguez Cano")

hotspots <- cases_hotspots_agebs19[loc,]
# Logistic Regression
glm.fit <- glm(hotspots_gi ~ DENV_2008 + DENV_2009 + 
                   DENV_2012 + DENV_2013  +
                   DENV_2015  + 
                   DENV_2019,
               data = hotspots, 
               family = binomial)

result <- parameters::model_parameters(glm.fit, 
                                      exponentiate = TRUE)

plotly::ggplotly(plot(result, size_text = 1))
```
  </div>
  <div class="box c">
```{r power_law_plot_tuxpan,dpi = 300, warning=FALSE, fig.align = "center", out.width = '100%',out.height='100%',fig.show = "hold"}
# Step 7. make the function por calculate the cumulative ####
funcumsum <- function(x){
    x$cumulative_n <- cumsum(x$n_cases)
    x$perc_cumsum_n <- round((cumsum(x$n_cases)/sum(x$n_cases))*100, digits = 1)
    #x$cumulative_ha <- cumsum(x$ha)
    #x$perc_cumsum_ha <- round((cumsum(x$ha)/sum(x$ha))*100, digits = 1)
    x$id <- 1
    x$id_cumsum <- cumsum(x$id)
    x$id_perc_cum <- round((cumsum(x$id)/nrow(x))*100, digits = 1)
    x
}
# step 8.

data_pareto <- hotspots   %>% 
    sf::st_drop_geometry()  %>% 
    dplyr::mutate(n_cases = rowSums(dplyr::select(., dplyr::starts_with("DENV"))),
                  loc = "locality")  %>% 
    dplyr::select(loc, n_cases, hotspots_gi)  %>% 
    dplyr::arrange(loc, desc(hotspots_gi), desc(n_cases))  %>% 
    dplyr::group_by(loc)  %>% 
    tidyr::nest()  %>% 
    dplyr::mutate(pareto_cases = purrr::map(data,
                                            funcumsum))  %>% 
    dplyr::select(-data)  %>% 
    tidyr::unnest(cols = c(pareto_cases))

# step 4. visualization of pareto rules ####
plotly::ggplotly(denhotspots::power_law_plot(x = data_pareto))  %>%  plotly::layout(showlegend = FALSE)

```
  </div>
  <div class="box d">
```{r gauge_blocks_tuxpan,fig.align = "center", out.height='100%', out.width = '100%', fig.width= 1.5, fig.height=1}
y_hot <- hotspots %>% dplyr::filter(hotspots_gi == 1)
centroid <- rgeomex::blocks_ine20_mx_centroid %>%
  sf::st_as_sf(coords = c("x", "y"), crs = 4326)
b_loc <- centroid[hotspots, ]
b_hot <- b_loc[y_hot, ]
flexdashboard::gauge(round((nrow(b_hot)/nrow(b_loc))*100, digits = 1),
      min = 0, max = 100, 
      symbol = '%', 
      label = "Manzanas",
      flexdashboard::gaugeSectors(success = c(0, 30), 
                                  warning = c(31, 50), 
                                  danger = c(51, 100),
                                  colors = c("success", "warning","danger")))
```
  </div>
  <div class="box e">
```{r gauge_AGEB_tuxpan, fig.align = "center", out.height='100%', out.width = '100%'}

y <- hotspots  %>%
    sf::st_drop_geometry() %>%
    dplyr::mutate(n_cases = rowSums(dplyr::select(., dplyr::starts_with("DENV"))),
                  loc = "locality") %>%
    dplyr::select(loc, n_cases, hotspots_gi) 
y_hot <- y %>% dplyr::filter(hotspots_gi == 1)
  
flexdashboard::gauge(round((nrow(y_hot)/nrow(y))*100, digits = 1),
      min = 0, max = 100, 
      symbol = '%', 
      label = "AGEBs",
      flexdashboard::gaugeSectors(success = c(0, 30), 
                                  warning = c(31, 50), 
                                  danger = c(51, 100),
                                  colors = c("success", "warning","danger")))
```
  </div>
<div class="box f">
```{r gauge_casos_tuxpan, out.height='90%', out.width = '90%', fig.align = "center"}

y <- hotspots  %>%
    sf::st_drop_geometry() %>%
    dplyr::mutate(n_cases = rowSums(dplyr::select(., dplyr::starts_with("DENV"))),
                  loc = "locality") %>%
    dplyr::select(loc, n_cases, hotspots_gi) 
y_hot <- y %>% dplyr::filter(hotspots_gi == 1)

flexdashboard::gauge(round((sum(y_hot$n_cases)/sum(y$n_cases))*100, digits = 1),
      min = 0, max = 100, 
      symbol = '%', 
      label = "Casos de Dengue",
      flexdashboard::gaugeSectors(success = c(10, 100), 
                   warning = c(6, 10), 
                   danger = c(0, 5),
                   colors = c("success", "warning","danger"))
      )
```
  </div>
</div>
</body>
</html>

### **<span style="color:#990000">Poza Rica</span>**
<html>
<head>
<style>
body {
  margin: 0px;
}

.wrapper {
    display: grid;
    grid-gap: 2px;
    grid-template-columns: 280px 280px 280px 550px;
    grid-template-rows: 165px 165px 165px 165px;
    background-color: #fff;
    color: "green";
  }

  .box {
    background-color: #cfcfc4;
    color: "green";
    border-radius: 2px;
    padding: 5px;
    font-size: 100%;

  }

  .a {
    grid-column: 1 / 4;
    grid-row: 1 / 4;
  }
  .b {
    grid-column: 4 ;
    grid-row: 1 / 3;
  }
  .c {
    grid-column: 4 ;
    grid-row: 3 / 5 ;
  }
  .d {
    grid-column: 3;
    grid-row: 4;
  }
  .e {
    grid-column: 2;
    grid-row: 4;
  }
  .f {
    grid-column: 1;
    grid-row: 4;
  }
</style>
</head>
<body>
<div class="wrapper">
  <div class="box a">
```{r hotspots_dengue_pozarica}
hotspots_map(cve_ent = "30",
             locality = "Poza Rica de Hidalgo",
             hotspots = cases_hotspots_agebs19,
             static_map = FALSE)

```
  </div>
  <div class="box b">
```{r forest_plot_pozarica, dpi = 300, fig.height= 5,fig.width = 7,fig.align = "center", out.height='100%', out.width = '100%',fig.show = "hold"}
 
# extract the locality
loc <- extract_locality(cve_edo = "30",
                        locality = "Poza Rica de Hidalgo")

hotspots <- cases_hotspots_agebs19[loc,]
# Logistic Regression
glm.fit <- glm(hotspots_gi ~ DENV_2008 + DENV_2009 + DENV_2010 +
                   DENV_2012 + DENV_2013 + DENV_2014 + DENV_2015  + 
                   DENV_2016 + DENV_2017 + DENV_2018 + DENV_2019 +
                       DENV_2020,
               data = hotspots, 
               family = binomial)

result <- parameters::model_parameters(glm.fit, 
                                      exponentiate = TRUE)

plotly::ggplotly(plot(result, size_text = 1))
```
  </div>
  <div class="box c">
```{r power_law_plot_pozarica,dpi = 300, warning=FALSE, fig.align = "center", out.width = '100%',out.height='100%',fig.show = "hold"}
# Step 7. make the function por calculate the cumulative ####
funcumsum <- function(x){
    x$cumulative_n <- cumsum(x$n_cases)
    x$perc_cumsum_n <- round((cumsum(x$n_cases)/sum(x$n_cases))*100, digits = 1)
    #x$cumulative_ha <- cumsum(x$ha)
    #x$perc_cumsum_ha <- round((cumsum(x$ha)/sum(x$ha))*100, digits = 1)
    x$id <- 1
    x$id_cumsum <- cumsum(x$id)
    x$id_perc_cum <- round((cumsum(x$id)/nrow(x))*100, digits = 1)
    x
}
# step 8.

data_pareto <- hotspots   %>% 
    sf::st_drop_geometry()  %>% 
    dplyr::mutate(n_cases = rowSums(dplyr::select(., dplyr::starts_with("DENV"))),
                  loc = "locality")  %>% 
    dplyr::select(loc, n_cases, hotspots_gi)  %>% 
    dplyr::arrange(loc, desc(hotspots_gi), desc(n_cases))  %>% 
    dplyr::group_by(loc)  %>% 
    tidyr::nest()  %>% 
    dplyr::mutate(pareto_cases = purrr::map(data,
                                            funcumsum))  %>% 
    dplyr::select(-data)  %>% 
    tidyr::unnest(cols = c(pareto_cases))

# step 4. visualization of pareto rules ####
plotly::ggplotly(denhotspots::power_law_plot(x = data_pareto))  %>%  plotly::layout(showlegend = FALSE)

```
  </div>
  <div class="box d">
```{r gauge_blocks_pozarica,fig.align = "center", out.height='100%', out.width = '100%', fig.width= 1.5, fig.height=1}
y_hot <- hotspots %>% dplyr::filter(hotspots_gi == 1)
centroid <- rgeomex::blocks_ine20_mx_centroid %>%
  sf::st_as_sf(coords = c("x", "y"), crs = 4326)
b_loc <- centroid[hotspots, ]
b_hot <- b_loc[y_hot, ]
flexdashboard::gauge(round((nrow(b_hot)/nrow(b_loc))*100, digits = 1),
      min = 0, max = 100, 
      symbol = '%', 
      label = "Manzanas",
      flexdashboard::gaugeSectors(success = c(0, 30), 
                                  warning = c(31, 50), 
                                  danger = c(51, 100),
                                  colors = c("success", "warning","danger")))
```
  </div>
  <div class="box e">
```{r gauge_AGEB_pozarica, fig.align = "center", out.height='100%', out.width = '100%'}

y <- hotspots  %>%
    sf::st_drop_geometry() %>%
    dplyr::mutate(n_cases = rowSums(dplyr::select(., dplyr::starts_with("DENV"))),
                  loc = "locality") %>%
    dplyr::select(loc, n_cases, hotspots_gi) 
y_hot <- y %>% dplyr::filter(hotspots_gi == 1)
  
flexdashboard::gauge(round((nrow(y_hot)/nrow(y))*100, digits = 1),
      min = 0, max = 100, 
      symbol = '%', 
      label = "AGEBs",
      flexdashboard::gaugeSectors(success = c(0, 30), 
                                  warning = c(31, 50), 
                                  danger = c(51, 100),
                                  colors = c("success", "warning","danger")))
```
  </div>
<div class="box f">
```{r gauge_casos_pozarica, out.height='90%', out.width = '90%', fig.align = "center"}

y <- hotspots  %>%
    sf::st_drop_geometry() %>%
    dplyr::mutate(n_cases = rowSums(dplyr::select(., dplyr::starts_with("DENV"))),
                  loc = "locality") %>%
    dplyr::select(loc, n_cases, hotspots_gi) 
y_hot <- y %>% dplyr::filter(hotspots_gi == 1)

flexdashboard::gauge(round((sum(y_hot$n_cases)/sum(y$n_cases))*100, digits = 1),
      min = 0, max = 100, 
      symbol = '%', 
      label = "Casos de Dengue",
      flexdashboard::gaugeSectors(success = c(10, 100), 
                   warning = c(6, 10), 
                   danger = c(0, 5),
                   colors = c("success", "warning","danger"))
      )
```
  </div>
</div>
</body>
</html>

### **<span style="color:#7d9029">Papantla</span>**

```{r, hotspots_dengue_papantla, echo=FALSE}
hotspots_map(cve_ent = "30",
             locality = "Papantla de Olearte",
             hotspots = cases_hotspots_agebs19,
             static_map = FALSE)

```

### **<span style="color:#7d9029">Martínez de la Torre</span>**

```{r, hotspots_dengue_martinez, echo=FALSE}
hotspots_map(cve_ent = "30",
             locality = "Martínez de la Torre",
             hotspots = cases_hotspots_agebs19,
             static_map = FALSE)

```


### **<span style="color:#7d9029">Xalapa</span>**

```{r, hotspots_dengue_xalapa, echo=FALSE}
hotspots_map(cve_ent = "30",
             locality = "Xalapa de Enríquez",
             hotspots = cases_hotspots_agebs19,
             static_map = TRUE)

```


### **<span style="color:#7d9029">Córdoba</span>**

```{r, hotspots_dengue_cordoba, echo=FALSE}
hotspots_map(cve_ent = "30",
             locality = "Córdoba",
             hotspots = cases_hotspots_agebs19,
             static_map = FALSE)

```

### **<span style="color:#7d9029">Orizaba</span>**

```{r, hotspots_dengue_orizaba, echo=FALSE}
hotspots_map(cve_ent = "30",
             locality = "Orizaba",
             hotspots = cases_hotspots_agebs19,
             static_map = FALSE)

```

### **<span style="color:#990000">Veracruz</span>**
<html>
<head>
<style>
body {
  margin: 0px;
}

.wrapper {
    display: grid;
    grid-gap: 2px;
    grid-template-columns: 280px 280px 280px 550px;
    grid-template-rows: 165px 165px 165px 165px;
    background-color: #fff;
    color: "green";
  }

  .box {
    background-color: #cfcfc4;
    color: "green";
    border-radius: 2px;
    padding: 5px;
    font-size: 100%;

  }

  .a {
    grid-column: 1 / 4;
    grid-row: 1 / 4;
  }
  .b {
    grid-column: 4 ;
    grid-row: 1 / 3;
  }
  .c {
    grid-column: 4 ;
    grid-row: 3 / 5 ;
  }
  .d {
    grid-column: 3;
    grid-row: 4;
  }
  .e {
    grid-column: 2;
    grid-row: 4;
  }
  .f {
    grid-column: 1;
    grid-row: 4;
  }
</style>
</head>
<body>
<div class="wrapper">
  <div class="box a">
```{r hotspots_dengue_veracruz}
hotspots_map(cve_ent = "30",
             locality = "Veracruz",
             hotspots = cases_hotspots_agebs19,
             static_map = FALSE)

```
  </div>
  <div class="box b">
```{r forest_plot_veracruz, dpi = 300, fig.height= 5,fig.width = 7,fig.align = "center", out.height='100%', out.width = '100%',fig.show = "hold"}
 
# extract the locality
loc <- extract_locality(cve_edo = "30",
                        locality = "Veracruz")

hotspots <- cases_hotspots_agebs19[loc,]
# Logistic Regression
glm.fit <- glm(hotspots_gi ~ DENV_2008 + DENV_2009 +  DENV_2012 + 
                   DENV_2013 + DENV_2014 +
                   DENV_2015 + DENV_2016 + DENV_2017 + DENV_2018 + 
                   DENV_2019 + DENV_2020 + DENV_2021,
               data = hotspots, 
               family = binomial)

result <- parameters::model_parameters(glm.fit, 
                                      exponentiate = TRUE)

plotly::ggplotly(plot(result, size_text = 1))
```
  </div>
  <div class="box c">
```{r power_law_plot_veracruz,dpi = 300, warning=FALSE, fig.align = "center", out.width = '100%',out.height='100%',fig.show = "hold"}
# Step 7. make the function por calculate the cumulative ####
funcumsum <- function(x){
    x$cumulative_n <- cumsum(x$n_cases)
    x$perc_cumsum_n <- round((cumsum(x$n_cases)/sum(x$n_cases))*100, digits = 1)
    #x$cumulative_ha <- cumsum(x$ha)
    #x$perc_cumsum_ha <- round((cumsum(x$ha)/sum(x$ha))*100, digits = 1)
    x$id <- 1
    x$id_cumsum <- cumsum(x$id)
    x$id_perc_cum <- round((cumsum(x$id)/nrow(x))*100, digits = 1)
    x
}
# step 8.

data_pareto <- hotspots   %>% 
    sf::st_drop_geometry()  %>% 
    dplyr::mutate(n_cases = rowSums(dplyr::select(., dplyr::starts_with("DENV"))),
                  loc = "locality")  %>% 
    dplyr::select(loc, n_cases, hotspots_gi)  %>% 
    dplyr::arrange(loc, desc(hotspots_gi), desc(n_cases))  %>% 
    dplyr::group_by(loc)  %>% 
    tidyr::nest()  %>% 
    dplyr::mutate(pareto_cases = purrr::map(data,
                                            funcumsum))  %>% 
    dplyr::select(-data)  %>% 
    tidyr::unnest(cols = c(pareto_cases))

# step 4. visualization of pareto rules ####
plotly::ggplotly(denhotspots::power_law_plot(x = data_pareto))  %>%  plotly::layout(showlegend = FALSE)

```
  </div>
  <div class="box d">
```{r gauge_blocks_veracruz,fig.align = "center", out.height='100%', out.width = '100%', fig.width= 1.5, fig.height=1}
y_hot <- hotspots %>% dplyr::filter(hotspots_gi == 1)
centroid <- rgeomex::blocks_ine20_mx_centroid %>%
  sf::st_as_sf(coords = c("x", "y"), crs = 4326)
b_loc <- centroid[hotspots, ]
b_hot <- b_loc[y_hot, ]
flexdashboard::gauge(round((nrow(b_hot)/nrow(b_loc))*100, digits = 1),
      min = 0, max = 100, 
      symbol = '%', 
      label = "Manzanas",
      flexdashboard::gaugeSectors(success = c(0, 30), 
                                  warning = c(31, 50), 
                                  danger = c(51, 100),
                                  colors = c("success", "warning","danger")))
```
  </div>
  <div class="box e">
```{r gauge_AGEB_veracruz, fig.align = "center", out.height='100%', out.width = '100%'}

y <- hotspots  %>%
    sf::st_drop_geometry() %>%
    dplyr::mutate(n_cases = rowSums(dplyr::select(., dplyr::starts_with("DENV"))),
                  loc = "locality") %>%
    dplyr::select(loc, n_cases, hotspots_gi) 
y_hot <- y %>% dplyr::filter(hotspots_gi == 1)
  
flexdashboard::gauge(round((nrow(y_hot)/nrow(y))*100, digits = 1),
      min = 0, max = 100, 
      symbol = '%', 
      label = "AGEBs",
      flexdashboard::gaugeSectors(success = c(0, 30), 
                                  warning = c(31, 50), 
                                  danger = c(51, 100),
                                  colors = c("success", "warning","danger")))
```
  </div>
<div class="box f">
```{r gauge_casos_veracruz, out.height='90%', out.width = '90%', fig.align = "center"}

y <- hotspots  %>%
    sf::st_drop_geometry() %>%
    dplyr::mutate(n_cases = rowSums(dplyr::select(., dplyr::starts_with("DENV"))),
                  loc = "locality") %>%
    dplyr::select(loc, n_cases, hotspots_gi) 
y_hot <- y %>% dplyr::filter(hotspots_gi == 1)

flexdashboard::gauge(round((sum(y_hot$n_cases)/sum(y$n_cases))*100, digits = 1),
      min = 0, max = 100, 
      symbol = '%', 
      label = "Casos de Dengue",
      flexdashboard::gaugeSectors(success = c(10, 100), 
                   warning = c(6, 10), 
                   danger = c(0, 5),
                   colors = c("success", "warning","danger"))
      )
```
  </div>
</div>
</body>
</html>

### **<span style="color:#7d9029">Cosomaloapan</span>**

```{r, hotspots_dengue_cosamaloapan, echo=FALSE}
hotspots_map(cve_ent = "30",
             locality = "Cosamaloapan",
             hotspots = cases_hotspots_agebs19,
             static_map = FALSE)

```
### **<span style="color:#7d9029">San Andres Tuxtla</span>**

```{r, hotspots_dengue_san_andres, echo=FALSE}
hotspots_map(cve_ent = "30",
             locality = "San Andres Tuxtla",
             hotspots = cases_hotspots_agebs19,
             static_map = FALSE)

```
### **<span style="color:#7d9029">Coatzacoalcos</span>**

```{r, hotspots_dengue_coatzacoalcos, echo=FALSE}
hotspots_map(cve_ent = "30",
             locality = "Coatzacoalcos",
             hotspots = cases_hotspots_agebs19,
             static_map = FALSE)

```
### **<span style="color:#7d9029">Minatitlán</span>**

```{r, hotspots_dengue_minatitlan, echo=FALSE}
hotspots_map(cve_ent = "30",
             locality = "Minatitán",
             hotspots = cases_hotspots_agebs19,
             static_map = FALSE)

```


**Vector Hotspots**
=====================================  


Column {.tabset}
-------------------------------------


### **<span style="color:#7d9029">Eggs</span>**

### **<span style="color:#7d9029">Adult</span>**


**Dengue Risk Maps**
=====================================  

Column {.tabset}
-------------------------------------

### **<span style="color:#7d9029">Tuxpan</span>**

```{r, risk_map_panuco, echo=FALSE}
risk <- risk_agebs(spde_model = spde_eggs_panuco_zinb1,
                          hotspots = cases_hotspots_agebs19,
                          locality = "Pánuco",
                          cve_ent = "30",
                          intensity_perc = 25)
risk_map(risk = risk, staticmap = FALSE)
```

### **<span style="color:#7d9029">Tuxpan</span>**
### **<span style="color:#7d9029">Poza Rica</span>**

```{r, risk_map_poza_rica, echo=FALSE}
risk <- risk_agebs(spde_model = spde_eggs_pozarica_zinb1,
                          hotspots = cases_hotspots_agebs19,
                          locality = "Poza Rica de Hidalgo",
                          cve_ent = "30",
                          intensity_perc = 25)
risk_map(risk = risk, staticmap = FALSE)
```


### **<span style="color:#7d9029">Papantla</span>**

```{r,  risk_map_papantla, echo=FALSE}

```

### **<span style="color:#7d9029">Martínez de la Torre</span>**

```{r, risk_map_martinez, echo=FALSE}
risk <- risk_agebs(spde_model = spde_eggs_martinez_zinb1,
                        hotspots = cases_hotspots_agebs19,
                        locality = "Martínes de la Torre",
                        cve_ent = "30",
                        intensity_perc = 25)

risk_map(risk = risk, staticmap = FALSE)
```


### **<span style="color:#7d9029">Xalapa</span>**

```{r, risk_map_xalapa, echo=FALSE}

```


### **<span style="color:#7d9029">Córdoba</span>**

```{r, risk_map_cordoba, echo=FALSE}
risk <- risk_agebs(spde_model = spde_eggs_cordoba_zinb1,
                        hotspots = cases_hotspots_agebs19,
                        locality = "Córdoba",
                        cve_ent = "30",
                        intensity_perc = 25)

risk_map(risk = risk, staticmap = FALSE)
```

### **<span style="color:#7d9029">Orizaba</span>**


```{r, risk_map_orizaba, echo=FALSE}
risk <- risk_agebs(spde_model = spde_eggs_orizaba_zinb1,
                        hotspots = cases_hotspots_agebs19,
                        locality = "Orizaba",
                        cve_ent = "30",
                        intensity_perc = 25)

risk_map(risk = risk, staticmap = FALSE)
```

### **<span style="color:#7d9029">Veracruz</span>**

```{r, risk_map_veracruz, echo=FALSE}
risk <- risk_agebs(spde_model = spde_eggs_veracruz_zinb1,
                        hotspots = cases_hotspots_agebs19,
                        locality = "Veracruz",
                        cve_ent = "30",
                        intensity_perc = 25)

risk_map(risk = risk, staticmap = FALSE)
```

### **<span style="color:#7d9029">Cosomaloapan</span>**


```{r, risk_map_cosomaloapan, echo=FALSE}
risk <- risk_agebs(spde_model = spde_eggs_cosamaloapan_zinb1,
                        hotspots = cases_hotspots_agebs19,
                        locality = "Cosoamaloapan",
                        cve_ent = "30",
                        intensity_perc = 25)

risk_map(risk = risk, staticmap = FALSE)
```

### **<span style="color:#7d9029">San Andres Tuxtla</span>**


```{r, risk_map_san_andres, echo=FALSE}
risk <- risk_agebs(spde_model = spde_eggs_san_andres_zinb1,
                        hotspots = cases_hotspots_agebs19,
                        locality = "San Andres Tuxtla",
                        cve_ent = "30",
                        intensity_perc = 25)

risk_map(risk = risk, staticmap = FALSE)

```

### **<span style="color:#7d9029">Coatzacoalcos</span>**

```{r, risk_map_coatzacoalcos, echo=FALSE}
risk <- risk_agebs(spde_model = spde_eggs_coatzacoalcos_zinb1,
                        hotspots = cases_hotspots_agebs19,
                        locality = "Coatzacoalcos",
                        cve_ent = "30",
                        intensity_perc = 25)

risk_map(risk = risk, staticmap = FALSE)
```
### **<span style="color:#7d9029">Minatitlán</span>**

```{r, risk_map_minatitlan, echo=FALSE}
risk <- risk_agebs(spde_model = spde_eggs_minatitlan_zinb1,
                        hotspots = cases_hotspots_agebs19,
                        locality = "Minatitlán",
                        cve_ent = "30",
                        intensity_perc = 25)

risk_map(risk = risk, staticmap = FALSE)
```




**Transmission Chains**
===================================== 



